_read_only: true
source: /
paths:
  uploads: uploads
  static: ''
editor:
  default_path: index.html
  site_files:
    editable:
      - "*.html"
  visual_editors:
    default: true
timezone: Europe/Belgrade
