source: /
output: dist

collections_config:
  pages:
    path: /
    output: false
    editable: true
    _enabled_editors:
      - visual
      - content

editor:
  default_path: index.html
  site_files:
    editable:
      - "*.html"

paths:
  uploads: uploads
  static: ''

timezone: Europe/Belgrade
