source: ""

build:
  install: npm install
  command: npm run build
  output: dist

paths:
  uploads: uploads
  static: ""

collections_config:
  pages:
    path: ""
    glob:
      - "*.html"
    icon: wysiwyg
