source: /
paths:
  uploads: uploads
  static: ''
editor:
  default_path: index.html
  site_files:
    editable:
      - "*.html"
collections_config:
  pages:
    path: /
    output: true
    editable: true
    icon: "file"
timezone: Europe/Belgrade
