source: /
paths:
  uploads: uploads
  static: ''
  output: dist
editor:
  default_path: index.html
  site_files:
    editable:
      - "*.html"
  visual_editors:
    default: true
build:
  output_path: dist
  command: npm run build
