source: /
paths:
  uploads: uploads
  static: ''
  output: dist
collections_config:
  pages:
    path: ''
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
editor:
  default_path: index.html
  site_files:
    editable:
      - '*.html'
  visual_editors:
    default: true
timezone: Etc/UTC
build:
  output_path: dist
  command: npm run build
